use std::{fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Failed to resolve workspace root");

    let nbis_root = workspace_root.join("crates/nbis-rs/ext/libbiomeval-10.0/nbis");
    let include_dir = nbis_root.join("include");
    let lib_dir = nbis_root.join("lib");
    let wsq_dir = lib_dir.join("wsq");
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    let mut files = vec![
        wsq_dir.join("encoder.c"),
        wsq_dir.join("decoder.c"),
        wsq_dir.join("globals.c"),
        wsq_dir.join("huff.c"),
        wsq_dir.join("ppi.c"),
        wsq_dir.join("tableio.c"),
        wsq_dir.join("tree.c"),
        wsq_dir.join("util.c"),
        wsq_dir.join("sd14util.c"),
        wsq_dir.join("cropcoeff.c"),
        lib_dir.join("dataio.c"),
        lib_dir.join("filesize.c"),
        lib_dir.join("allocfet.c"),
        lib_dir.join("delfet.c"),
        lib_dir.join("freefet.c"),
        lib_dir.join("lkupfet.c"),
        lib_dir.join("strfet.c"),
        lib_dir.join("updatfet.c"),
        lib_dir.join("extrfet.c"),
        lib_dir.join("jpegl/huff.c"),
        lib_dir.join("jpegl/huftable.c"),
        lib_dir.join("jpegl/tableio.c"),
        lib_dir.join("computil.c"),
        lib_dir.join("nistcom.c"),
        lib_dir.join("fatalerr.c"),
        lib_dir.join("syserr.c"),
    ];

    if target_os == "windows" {
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));

        // Generate stub POSIX headers that don't exist on MSVC.
        // NBIS sources include these but don't actually use their contents
        // in the subset of files we compile (WSQ/JPEGL/FET).
        let compat_dir = out_dir.join("compat");
        fs::create_dir_all(&compat_dir).expect("failed to create compat dir");

        // filesize.c includes <unistd.h>
        fs::write(
            compat_dir.join("unistd.h"),
            "/* build.rs stub for MSVC */\n",
        )
        .expect("failed to write stub unistd.h");

        // lkupfet.c, extrfet.c, updatfet.c include <strings.h>
        // Map strcasecmp -> _stricmp in case anything references it.
        fs::write(
            compat_dir.join("strings.h"),
            "#ifndef _COMPAT_STRINGS_H\n\
             #define _COMPAT_STRINGS_H\n\
             #include <string.h>\n\
             #define strcasecmp  _stricmp\n\
             #define strncasecmp _strnicmp\n\
             #endif\n",
        )
        .expect("failed to write stub strings.h");

        let nbis_debug_c = out_dir.join("nbis_debug.c");
        fs::write(
            &nbis_debug_c,
            "/* Generated by build.rs: required by NBIS WSQ/JPEGL sources on MSVC. */\nint debug = 0;\n",
        )
        .expect("failed to write generated NBIS debug definition");
        files.push(nbis_debug_c);
    }

    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
    }

    let mut build = cc::Build::new();
    build
        .include(&include_dir)
        .define("NOVERBOSE", None)
        .define("__NBISLE__", None)
        .flag_if_supported("-w");

    // On Windows: suppress MSVC deprecation warnings and add compat/ include
    // dir so the stub unistd.h is found.
    if target_os == "windows" {
        build.define("_CRT_SECURE_NO_WARNINGS", None);
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
        build.include(out_dir.join("compat"));
    }

    build.files(&files).compile("nbis_wsq");

    if target_os != "windows" {
        println!("cargo:rustc-link-lib=m");
    }
}
